---
title: "ETFs"
description: |
  Work in progess.
author:
  - name: Fahim Ahmed 
    url: 
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggdist)
library(distill)
```

```{r, include = FALSE}
x <- read_csv("ETFs.csv", col_types = cols(
  fund_symbol = col_character(),
  fund_extended_name = col_character(),
  fund_family = col_character(),
  inception_date = col_date(format = ""),
  category = col_character(),
  investment_strategy = col_character(),
  investment_type = col_character(),
  size_type = col_character(),
  currency = col_character(),
  fund_net_annual_expense_ratio = col_double(),
  category_net_annual_expense_ratio = col_double(),
  asset_stocks = col_double(),
  asset_bonds = col_double(),
  price_earnings_ratio = col_double(),
  price_book_ratio = col_double(),
  price_sales_ratio = col_double(),
  price_cashflow_ratio = col_double(),
  sector_basic_materials = col_double(),
  sector_consumer_cyclical = col_double(),
  sector_financial_services = col_double(),
  sector_real_estate = col_double(),
  sector_consumer_defensive = col_double(),
  sector_healthcare = col_double(),
  sector_utilities = col_double(),
  sector_communication_services = col_double(),
  sector_energy = col_double(),
  sector_industrials = col_double(),
  sector_technology = col_double(),
  credit_us_government = col_double(),
  credit_aaa = col_double(),
  credit_aa = col_double(),
  credit_a = col_double(),
  credit_bbb = col_double(),
  credit_bb = col_double(),
  credit_b = col_double(),
  credit_below_b = col_double(),
  credit_other_ratings = col_double(),
  net_asset_value = col_double(),
  fund_yield = col_double(),
  top10_holdings = col_character(),
  fund_return_ytd = col_double(),
  category_return_ytd = col_double(),
  fund_return_1month = col_double(),
  category_return_1month = col_double(),
  fund_return_3months = col_double(),
  category_return_3months = col_double(),
  fund_return_1year = col_double(),
  category_return_1year = col_double(),
  fund_return_3years = col_double(),
  category_return_3years = col_double(),
  fund_return_5years = col_double(),
  category_return_5years = col_double(),
  fund_return_10years = col_double(),
  category_return_10years = col_double(),
  fund_return_2019 = col_double(),
  category_return_2019 = col_logical(),
  fund_return_2018 = col_double(),
  category_return_2018 = col_logical(),
  fund_return_2017 = col_double(),
  category_return_2017 = col_logical(),
  fund_return_2016 = col_double(),
  category_return_2016 = col_logical(),
  fund_return_2015 = col_double(),
  category_return_2015 = col_double(),
  fund_return_2014 = col_double(),
  category_return_2014 = col_double(),
  fund_return_2013 = col_double(),
  category_return_2013 = col_double(),
  fund_return_2012 = col_double(),
  category_return_2012 = col_double(),
  fund_return_2011 = col_double(),
  category_return_2011 = col_double(),
  fund_return_2010 = col_double(),
  category_return_2010 = col_double(),
  years_up = col_double(),
  years_down = col_double(),
  fund_alpha_3years = col_double(),
  category_alpha_3years = col_double(),
  fund_alpha_5years = col_double(),
  category_alpha_5years = col_double(),
  fund_alpha_10years = col_double(),
  category_alpha_10years = col_double(),
  fund_beta_3years = col_double(),
  category_beta_3years = col_double(),
  fund_beta_5years = col_double(),
  category_beta_5years = col_double(),
  fund_beta_10years = col_double(),
  category_beta_10years = col_double(),
  fund_mean_annual_return_3years = col_double(),
  category_mean_annual_return_3years = col_double(),
  fund_mean_annual_return_5years = col_double(),
  category_mean_annual_return_5years = col_double(),
  fund_mean_annual_return_10years = col_double(),
  category_mean_annual_return_10years = col_double(),
  fund_r_squared_3years = col_double(),
  category_r_squared_3years = col_double(),
  fund_r_squared_5years = col_double(),
  category_r_squared_5years = col_double(),
  fund_r_squared_10years = col_double(),
  category_r_squared_10years = col_double(),
  fund_standard_deviation_3years = col_double(),
  category_standard_deviation_3years = col_double(),
  fund_standard_deviation_5years = col_double(),
  category_standard_deviation_5years = col_double(),
  fund_standard_deviation_10years = col_double(),
  category_standard_deviation_10years = col_double(),
  fund_sharpe_ratio_3years = col_double(),
  category_sharpe_ratio_3years = col_double(),
  fund_sharpe_ratio_5years = col_double(),
  category_sharpe_ratio_5years = col_double(),
  fund_sharpe_ratio_10years = col_double(),
  category_sharpe_ratio_10years = col_double(),
  fund_treynor_ratio_3years = col_double(),
  category_treynor_ratio_3years = col_double(),
  fund_treynor_ratio_5years = col_double(),
  category_treynor_ratio_5years = col_character(),
  fund_treynor_ratio_10years = col_double(),
  category_treynor_ratio_10years = col_double()
))
```

```{r, echo = FALSE}
x %>% 
  select(fund_symbol, fund_family, fund_return_1year) %>%
  group_by(fund_family) %>%
  summarize(avg_return = mean(fund_return_1year)) %>%
  arrange(desc(avg_return)) %>%
  head(5) %>%
  mutate(fund_family = fct_infreq(fund_family)) %>%
  mutate(fund_family = fct_rev(fund_family)) %>%
  ggplot(mapping = aes(x = fct_reorder(fund_family, avg_return), y = avg_return)) +
    geom_col(fill = "LightBlue") +
    theme_classic() +
    labs(title = "Top 5 ETF Managers",
       subtitle = "ARK ETF Trust was the best performing ETF fund, based on 1 year of performance",
       x = "Fund Family",
       y = "Average ETF Return (Percent)",
       caption = "Source: Yahoo Finance")
```

```{r, warning = FALSE, echo = FALSE} 
# Does fund_yield correlate to higher returns? 
# warning = FALSE as the warning is harmless. It is caused by xlim() cropping out two datapoints.
x %>%
  select(fund_symbol, fund_yield, fund_return_1year) %>%
  ggplot(mapping = aes(x = fund_yield, y = fund_return_1year)) +
    geom_point(alpha = 0.2) +
    xlim(c(0, 20)) +
    geom_smooth(method = "lm", formula = y~x, se = FALSE) +
    theme_classic() +
    labs(title = "Fund Yield vs. Annual Return",
         subtitle = "Yield has a negative correlation with annual return.",
         x = "Fund Yield",
         y = "Annual Return (Percent)",
         caption = "Source: Yahoo Finance")

```

```{r, echo = FALSE}
# Which sector did the best in the past year? Graph where x = sector_basic_materials, and y = fund_return_1year. do the same for each sector.
```

```{r sector_data, echo = FALSE}
# Rather than having a column for each sector, replace it with a column named "ratio" (or something else, as it's more of a percentage) containing the ratio of the sector and "sector" containing the name of the sector
sector_data <- x %>%
  select(fund_symbol, sector_basic_materials : sector_technology, fund_return_1year, fund_return_5years) %>%
  pivot_longer(names_to = "sector",
               values_to = "ratio",
               cols = c(-fund_symbol, -fund_return_1year, -fund_return_5years)) %>%
  mutate(sector = str_replace(sector, "sector_", "")) %>% # remove sector_ from the start of each row
  mutate(sector = str_replace(sector, "_", " ")) %>% # make the values more "word-like"
  mutate(sector = str_to_title(sector)) %>%
  filter(ratio >= 50)
```

```{r, echo = FALSE, include = FALSE}
sector_data %>%
  ggplot(mapping = aes(ratio, fund_return_1year, color = sector)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  facet_wrap(~ sector) +
  theme_classic() +
  labs(title = "Percentage of Investments in Specific Sectors vs. Annual Return",
       x = "Percentage in Given Sector",
       y = "Annual Return",
       color = "Sector",
       caption = "Source: Yahoo Finance")
```
```{r, echo = FALSE}
#Not every fund is included (as not every fund has >= 50% invested in a single portion). It takes the one that has the majority in a sector (as filtering by >= 50 only shows ones with majority in a specific sector).
# Can narrow further by doing >= 75
# Maybe also do a graph for one with the least in a specific sector, to show which sectors should be avoided for maximum gains (as you can see which funds performed the best with the least in one sector)?

# Add a vertical line at x = 0, to show which side is positive & negative returns.

sector_data %>%
  ggplot(mapping = aes(fund_return_1year, sector)) +
  stat_slab() +
  theme_classic() +
  labs(title = "Sectors vs. Annual Return",
       subtitle = "The technology sector performed the best over the past year.",
       x = "Annual Return",
       y = "Sector",
       caption = "Source: Yahoo Finance")
```
```{r, echo = FALSE}
#Not every fund is included (as not every fund has >= 50% invested in a single portion). It takes the one that has the majority in a sector (as filtering by >= 50 only shows ones with majority in a specific sector).
# Can narrow further by doing >= 75
# Maybe also do a graph for one with the least in a specific sector, to show which sectors should be avoided for maximum gains (as you can see which funds performed the best with the least in one sector)?

# Add a vertical line at x = 0, to show which side is positive & negative returns.

sector_data %>%
  drop_na(fund_return_5years) %>%
  ggplot(mapping = aes(fund_return_5years, sector)) +
  stat_slab() +
  theme_classic() +
  labs(title = "Sectors vs. Average Annual Returns Over 5 Years",
       subtitle = "In the longterm, the technology sector performed the best, \nwhile the energy sector had negative returns.",
       x = "Annual Return",
       y = "Sector",
       caption = "Source: Yahoo Finance")
```

```{r, echo = FALSE}
# Maybe do something with investment_type to determine how far behind blend or value investments are compared to growth. Make a 1 year graph and a 5 year graph.
#maybe make the first bar red, because it lost money
x %>%
  select(investment_type, fund_return_1year) %>%
  drop_na() %>%
  group_by(investment_type) %>%
  summarize(avg_return = mean(fund_return_1year)) %>%
  mutate(investment_type = fct_infreq(investment_type)) %>% #what does this row & the row below do?
  mutate(investment_type = fct_rev(investment_type)) %>%
  ggplot(mapping = aes(x = fct_reorder(investment_type, avg_return), y = avg_return)) +
    geom_col(fill = "LightBlue") +
    theme_classic() +
    labs(title = "Investment Type vs. Annual Returns",
         subtitle = "Riskier growth focused investments delivered high returns, \nwhile value oriented investments lost money.",
         x = "Investment Type",
         y = "Annual Return")
```

```{r, echo = FALSE}
x %>%
  select(investment_type, fund_return_5years) %>%
  drop_na() %>%
  group_by(investment_type) %>%
  summarize(avg_return = mean(fund_return_5years)) %>%
  mutate(investment_type = fct_infreq(investment_type)) %>% #what does this row & the row below do?
  mutate(investment_type = fct_rev(investment_type)) %>%
  ggplot(mapping = aes(x = fct_reorder(investment_type, avg_return), y = avg_return)) +
    geom_col(fill = "LightBlue") +
    theme_classic() +
    labs(title = "Investment Type vs. Average Annual Returns Over 5 Years",
         subtitle = "In the long term, riskier growth focused investments delivered higher returns.",
         x = "Investment Type",
         y = "Average Annual Return")
```

```{r, echo = FALSE}
# Maybe add in a graph that analyses when most of these ETF's were made (and if there was any event during that time).
```

